
set_away_mode:
  description: Turn away mode on/off for a thermostat

  fields:
    entity_id:
      description: Name(s) of entities to change
      example: 'light.kitchen'

    away_mode:
      description: New value of away mode
      example: true

set_temperature:
  description: Set temperature of thermostat

  fields:
    entity_id:
      description: Name(s) of entities to change
      example: 'light.kitchen'

    temperature:
      description: New target temperature for thermostat
      example: 25
