homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 39.9289
  longitude: 116.3883
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai

# Track the sun
#sun:

# Show links to resources in log and frontend
#introduction:

# Enables support for tracking state changes over time.
history:

# Enables the frontend
frontend:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend
#conversation:

# Checks for available updates
#updater:

# View all events in a logbook
logbook:



switch:
      platform: mqtt
      command_topic: "command_arduino_switch"
      state_topic: "state_arduino_switch"
      optimistic: true
lock:
      platform: demo

#hello_world:
#           platform: demo

#example:
#        target: hello_world.Hello_World
mqtt:
      broker: 127.0.0.1
#      broker: m10.cloudmqtt.com
#      port: 12102
#      username: olqfiibh
#      password: mrK3YHshj42T

#mqtt_example:





